name: CI/CD with ArgoCD

on:
  push:
    branches: [JAVASCRIPT]
permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ اسحب الكود
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ تسجيل الدخول لـ GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password:
            ${{ secrets.GITHUB_TOKEN }}
            
      # 3️⃣ بناء الصورة ودفعها
      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/demo-app:latest
          docker build -t $IMAGE ./app
          docker push $IMAGE
